//! Action definitions registry data — the Zig port of reavim's
//! definitions/extended_defaults/actions.lua (the variant we ship; where it
//! differs from defaults/actions.lua the extended variant wins).
//! Generated from port/actions_inventory.md, entries kept in Lua file order.
//! Lua-function actions are NOT ported yet — they need native Zig fns; see
//! the trailing comment block for the full skip list grouped by module.
//! Mode/state funcs (SetModeNormal etc.) already live in lib_state.zig.
const actions = @import("actions.zig");

pub const entries = [_]actions.Entry{
    // midi item activation / fx
    .{ .name = "ActivateNextMidiItem", .def = .{ .steps = &.{.{ .cmd = 40833 }}, .midi_command = true } },
    .{ .name = "ActivatePrevMidiItem", .def = .{ .steps = &.{.{ .cmd = 40834 }}, .midi_command = true } },
    .{ .name = "AddFx", .def = .{ .steps = &.{.{ .cmd = 40271 }} } },
    .{ .name = "AddNextNoteToSelection", .def = .{ .steps = &.{.{ .cmd = 40422 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "AddPrevNoteToSelection", .def = .{ .steps = &.{.{ .cmd = 40421 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "InsertVirtualInstrumentTrack", .def = .{ .steps = &.{.{ .cmd = 40701 }} } },
    .{ .name = "InsertClickTrack", .def = .{ .steps = &.{.{ .named = "_SWS_AWINSERTCLICKTRK" }} } },
    .{ .name = "AllTrackItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsOnTrack" }, .{ .action = "SelectedItems" }, .{ .action = "RestoreItemSelection" } } } },
    .{ .name = "AllTracks", .def = .{ .steps = &.{.{ .cmd = 40296 }} } },
    .{ .name = "ArmAllEnvelopes", .def = .{ .steps = &.{.{ .named = "_S&M_ARMALLENVS" }} } },
    .{ .name = "ArmSelectedTracks", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELTRAX_RECARMED" }} } },
    .{ .name = "ArmTracks", .def = .{ .steps = &.{.{ .cmd = 9 }} } },
    .{ .name = "AutomationItem", .def = .{ .steps = &.{.{ .cmd = 42197 }} } },
    .{ .name = "AutoRenameTake", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_AUTORENAMETAKES" }} } },
    .{ .name = "CleanProjectDirectory", .def = .{ .steps = &.{.{ .cmd = 40098 }} } },
    .{ .name = "ClearAllEnvelope", .def = .{ .steps = &.{.{ .named = "_S&M_REMOVE_ALLENVS" }} } },
    .{ .name = "ClearAllRecordArm", .def = .{ .steps = &.{.{ .cmd = 40491 }} } },
    .{ .name = "ClearEnvelope", .def = .{ .steps = &.{.{ .cmd = 40065 }} } },
    .{ .name = "ClearNoteSelection", .def = .{ .steps = &.{.{ .cmd = 40214 }}, .midi_command = true } },
    // fx windows
    .{ .name = "CloseAllFxChainsAndWindows", .def = .{ .steps = &.{ .{ .action = "CloseAllFx" }, .{ .action = "CloseAllFxChain" } } } },
    .{ .name = "CloseAllFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_WNCLS4" }} } },
    .{ .name = "CloseAllFx", .def = .{ .steps = &.{.{ .named = "_S&M_WNCLS3" }} } },
    .{ .name = "CloseFloatingFxWindows", .def = .{ .steps = &.{.{ .named = "_S&M_WNCLS3" }} } },
    .{ .name = "PlayFromMouseAndSoloTrack", .def = .{ .steps = &.{.{ .named = "_BR_CONT_PLAY_MOUSE_SOLO_TRACK" }} } },
    .{ .name = "PlayFromEditCursorAndSoloTrackUnderMouse", .def = .{ .steps = &.{.{ .named = "_BR_TOGGLE_PLAY_EDIT_SOLO_TRACK" }} } },
    .{ .name = "CloseFx", .def = .{ .steps = &.{ .{ .action = "CloseFxChains" }, .{ .action = "CloseFxWindows" } } } },
    .{ .name = "CloseFxWindows", .def = .{ .steps = &.{.{ .named = "_S&M_WNCLS5" }} } },
    .{ .name = "CloseFxChains", .def = .{ .steps = &.{.{ .named = "_S&M_WNCLS4" }} } },
    .{ .name = "CloseProject", .def = .{ .steps = &.{.{ .cmd = 40860 }} } },
    // extended_defaults: prepends LoadTrkScreenSet1 before closing
    .{ .name = "CloseWindow", .def = .{ .steps = &.{ .{ .action = "LoadTrkScreenSet1" }, .{ .cmd = 2 } }, .midi_command = true } },
    // track color
    .{ .name = "ColorTrack", .def = .{ .steps = &.{.{ .cmd = 40360 }}, .prefix_repetition_count = true } },
    .{ .name = "ColorTrackGradient", .def = .{ .steps = &.{.{ .named = "_SWS_TRACKGRAD" }} } },
    .{ .name = "ColorTrackWithTrackAbove", .def = .{ .steps = &.{.{ .named = "_SWS_COLTRACKPREV" }} } },
    .{ .name = "ColorTrackWithTrackBelow", .def = .{ .steps = &.{.{ .named = "_SWS_COLTRACKNEXT" }} } },
    // copy / cut
    .{ .name = "CopyAndFitByLooping", .def = .{ .steps = &.{.{ .cmd = 41319 }} } },
    .{ .name = "CopyEnvelope", .def = .{ .steps = &.{.{ .cmd = 40035 }} } },
    .{ .name = "CopyEnvelopePoints", .def = .{ .steps = &.{.{ .cmd = 40324 }} } },
    .{ .name = "CopySelectedEnvelopePoints", .def = .{ .steps = &.{.{ .cmd = 40335 }} } },
    .{ .name = "CopyFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_SMART_CPY_FXCHAIN" }} } },
    .{ .name = "CopyItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "CopySelectedAreaOfItems" }, .{ .action = "RestoreItemSelection" } } } },
    .{ .name = "CopyNotes", .def = .{ .steps = &.{ .{ .action = "SelectNotes" }, .{ .action = "CopySelectedEvents" } } } },
    .{ .name = "CopySelectedAreaOfItems", .def = .{ .steps = &.{.{ .cmd = 40060 }} } },
    .{ .name = "CopySelectedEvents", .def = .{ .steps = &.{.{ .cmd = 40733 }}, .midi_command = true } },
    .{ .name = "CopySelectedItems", .def = .{ .steps = &.{.{ .cmd = 40698 }} } },
    .{ .name = "CopyTrack", .def = .{ .steps = &.{.{ .cmd = 40210 }} } },
    .{ .name = "CropToActiveTake", .def = .{ .steps = &.{.{ .cmd = 40131 }} } },
    .{ .name = "CutEnvelopePoints", .def = .{ .steps = &.{.{ .cmd = 40325 }} } },
    .{ .name = "CutFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_COPYFXCHAIN6" }} } },
    .{ .name = "CutInputFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_CUT_INFXCHAIN" }} } },
    .{ .name = "Overdub", .def = .{ .steps = &.{ .{ .action = "CopyTrack" }, .{ .action = "UnarmSelectedTracks" }, .{ .action = "Paste" }, .{ .action = "NextTrack" }, .{ .action = "StartStop" }, .{ .action = "ToggleRecord" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "CutSelectedItems" } } } },
    .{ .name = "CutItemFxChain", .def = .{ .steps = &.{ .{ .action = "CopyItemFxChain" }, .{ .action = "ClearItemFxChain" } } } },
    .{ .name = "CopyItemFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_COPYFXCHAIN1" }} } },
    .{ .name = "ClearItemFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_CLRFXCHAIN2" }} } },
    .{ .name = "CutItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsAndSplit" }, .{ .action = "CutSelectedItems" }, .{ .action = "RestoreItemSelection" } } } },
    .{ .name = "MoveItemContentToEditCursor", .def = .{ .steps = &.{.{ .cmd = 41308 }} } },
    .{ .name = "MoveItemToEditCursor", .def = .{ .steps = &.{.{ .cmd = 41205 }} } },
    .{ .name = "CutNotes", .def = .{ .steps = &.{ .{ .action = "SelectNotes" }, .{ .action = "CutSelectedEvents" } } } },
    .{ .name = "CutSelectedEvents", .def = .{ .steps = &.{.{ .cmd = 40012 }}, .midi_command = true } },
    .{ .name = "CutSelectedItems", .def = .{ .steps = &.{.{ .cmd = 40699 }} } },
    .{ .name = "CutTrack", .def = .{ .steps = &.{ .{ .action = "CopyTrack" }, .{ .action = "RemoveTrack" }, .{ .action = "SelectLastTouchedTrack" } } } },
    // folders / takes / misc cycling
    .{ .name = "CycleFolderCollapsedState", .def = .{ .steps = &.{.{ .cmd = 1042 }} } },
    .{ .name = "CycleFolderState", .def = .{ .steps = &.{.{ .cmd = 1041 }} } },
    .{ .name = "CycleItemFadeInShape", .def = .{ .steps = &.{.{ .cmd = 41520 }}, .prefix_repetition_count = true } },
    .{ .name = "CycleItemFadeOutShape", .def = .{ .steps = &.{.{ .cmd = 41527 }}, .prefix_repetition_count = true } },
    .{ .name = "CycleRecordMonitor", .def = .{ .steps = &.{.{ .cmd = 40495 }} } },
    .{ .name = "CycleRippleEditMode", .def = .{ .steps = &.{.{ .cmd = 1155 }} } },
    .{ .name = "DeleteActiveTake", .def = .{ .steps = &.{.{ .cmd = 40129 }}, .prefix_repetition_count = true } },
    .{ .name = "DeleteEnvelope", .def = .{ .steps = &.{.{ .cmd = 40333 }} } },
    .{ .name = "DeleteItem", .def = .{ .steps = &.{.{ .cmd = 40006 }} } },
    .{ .name = "DeleteNote", .def = .{ .steps = &.{.{ .cmd = 40002 }}, .midi_command = true } },
    .{ .name = "DeleteTimeline", .def = .{ .steps = &.{.{ .cmd = 40201 }} } },
    .{ .name = "InsertTrackFromTemplate", .def = .{ .steps = &.{.{ .cmd = 46000 }} } },
    // extended_defaults variants (defaults only insert the track)
    .{ .name = "EnterTrackAbove", .def = .{ .steps = &.{ .{ .action = "InsertTrackAbove" }, .{ .action = "ColorTrackWithTrackBelow" }, .{ .action = "RenameTrack" } } } },
    .{ .name = "EnterTrackBelow", .def = .{ .steps = &.{ .{ .action = "InsertTrackBelow" }, .{ .action = "ColorTrackWithTrackAbove" }, .{ .action = "RenameTrack" } } } },
    .{ .name = "EventSelectionEnd", .def = .{ .steps = &.{.{ .cmd = 40639 }}, .midi_command = true } },
    .{ .name = "EventSelectionStart", .def = .{ .steps = &.{.{ .cmd = 40440 }}, .midi_command = true } },
    // time signature markers
    .{ .name = "AddTimeSignatureMarker", .def = .{ .steps = &.{.{ .cmd = 40256 }} } },
    .{ .name = "EditTimeSignatureMarker", .def = .{ .steps = &.{.{ .cmd = 40618 }} } },
    .{ .name = "DeleteTimeSignatureMarker", .def = .{ .steps = &.{.{ .cmd = 40617 }} } },
    .{ .name = "NextTimeSignatureMarker", .def = .{ .steps = &.{.{ .cmd = 41821 }} } },
    .{ .name = "PrevTimeSignatureMarker", .def = .{ .steps = &.{.{ .cmd = 41820 }} } },
    // item fitting / glue
    .{ .name = "GlueItemsIgnoringTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40362 }} } },
    .{ .name = "FitByLoopingNoExtend", .def = .{ .steps = &.{ .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "GlueItemsIgnoringTimeSelection" }, .{ .action = "FitSelectedItemsByLooping" } } } },
    .{ .name = "ToggleShowTempoEnvelope", .def = .{ .steps = &.{.{ .cmd = 41046 }} } },
    // extended_defaults names this ToggleShowMaster (defaults: MasterTrack)
    .{ .name = "ToggleShowMaster", .def = .{ .steps = &.{.{ .cmd = 40075 }} } },
    .{ .name = "FitByLooping", .def = .{ .steps = &.{ .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "FitSelectedItemsByLooping" } } } },
    .{ .name = "FitByPadding", .def = .{ .steps = &.{ .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "FitSelectedItemsByPadding" } } } },
    .{ .name = "FitByStretching", .def = .{ .steps = &.{ .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "FitSelectedItemsByStretching" } } } },
    .{ .name = "FitEnvelopePoints", .def = .{ .steps = &.{.{ .named = "_BR_FIT_ENV_POINTS_TO_TIMESEL" }} } },
    .{ .name = "FitSelectedItemsByLooping", .def = .{ .steps = &.{.{ .cmd = 41386 }} } },
    .{ .name = "FitSelectedItemsByPadding", .def = .{ .steps = &.{.{ .cmd = 41385 }} } },
    .{ .name = "FitSelectedItemsByStretching", .def = .{ .steps = &.{.{ .cmd = 41206 }} } },
    .{ .name = "FitNotes", .def = .{ .steps = &.{.{ .cmd = 40754 }}, .midi_command = true } },
    .{ .name = "FocusMain", .def = .{ .steps = &.{.{ .named = "_S&M_WNMAIN" }} } },
    // folders
    .{ .name = "FolderChildren", .def = .{ .steps = &.{ .{ .action = "SelectFolderChildren" }, .{ .action = "ScrollToSelectedTracks" } } } },
    .{ .name = "FolderParent", .def = .{ .steps = &.{ .{ .action = "SelectFolderParent" }, .{ .action = "ScrollToSelectedTracks" } } } },
    .{ .name = "Folder", .def = .{ .steps = &.{ .{ .action = "SelectFolder" }, .{ .action = "ScrollToSelectedTracks" } } } },
    .{ .name = "FreezeTrack", .def = .{ .steps = &.{.{ .cmd = 41223 }} } },
    .{ .name = "GlueItemIgnoringTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40362 }} } },
    .{ .name = "GlueItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItems" }, .{ .action = "GlueSelectedItemsInTimeSelection" }, .{ .action = "RestoreItemSelection" } } } },
    .{ .name = "GlueSelectedItemsInTimeSelection", .def = .{ .steps = &.{.{ .cmd = 41588 }} } },
    .{ .name = "GoToEnd", .def = .{ .steps = &.{.{ .cmd = 40037 }}, .midi_command = true } },
    .{ .name = "GoToStart", .def = .{ .steps = &.{.{ .cmd = 40036 }}, .midi_command = true } },
    .{ .name = "GroupItems", .def = .{ .steps = &.{.{ .cmd = 40032 }} } },
    .{ .name = "HealItemsSplits", .def = .{ .steps = &.{.{ .cmd = 40548 }} } },
    .{ .name = "CreateMeasures", .def = .{ .steps = &.{.{ .cmd = 40338 }} } },
    .{ .name = "CreateProjectTempo", .def = .{ .steps = &.{.{ .cmd = 40843 }} } },
    .{ .name = "InnerFolderAndParent", .def = .{ .steps = &.{ .{ .action = "FolderParent" }, .{ .action = "SelectFolder" } } } },
    .{ .name = "InnerFolder", .def = .{ .steps = &.{ .{ .action = "FolderParent" }, .{ .action = "SelectOnlyFoldersChildren" } } } },
    // insertion
    .{ .name = "InsertAutomationItem", .def = .{ .steps = &.{.{ .cmd = 42082 }} } },
    .{ .name = "InsertDefaultSizeNote", .def = .{ .steps = &.{.{ .cmd = 40051 }}, .midi_command = true } },
    .{ .name = "InsertNote", .def = .{ .steps = &.{ .{ .action = "MidiTimeSelectionStart" }, .{ .action = "InsertDefaultSizeNote" }, .{ .action = "MidiTimeSelectionStart" }, .{ .action = "SelectNearestNote" }, .{ .action = "FitNotes" } } } },
    .{ .name = "InsertOrExtendMidiItem", .def = .{ .steps = &.{.{ .cmd = 42069 }} } },
    .{ .name = "InsertTrackAbove", .def = .{ .steps = &.{.{ .named = "_SWS_INSRTTRKABOVE" }}, .prefix_repetition_count = true } },
    .{ .name = "InsertTrackBelow", .def = .{ .steps = &.{.{ .cmd = 40001 }}, .prefix_repetition_count = true } },
    .{ .name = "Insert4EnvelopePointsAtTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40726 }} } },
    .{ .name = "ShiftEnvelopePointsUp", .def = .{ .steps = &.{.{ .cmd = 41180 }}, .prefix_repetition_count = true } },
    .{ .name = "ShiftEnvelopePointsUpATinyBit", .def = .{ .steps = &.{.{ .cmd = 42381 }}, .prefix_repetition_count = true } },
    .{ .name = "ShiftEnvelopePointsDown", .def = .{ .steps = &.{.{ .cmd = 41181 }}, .prefix_repetition_count = true } },
    .{ .name = "ShiftEnvelopePointsDownATinyBit", .def = .{ .steps = &.{.{ .cmd = 42382 }}, .prefix_repetition_count = true } },
    .{ .name = "InvertVoicingDownwards", .def = .{ .steps = &.{.{ .cmd = 40910 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "InvertVoicingUpwards", .def = .{ .steps = &.{.{ .cmd = 40909 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "ApplyFxToItem", .def = .{ .steps = &.{.{ .cmd = 40209 }} } },
    .{ .name = "ItemNormalize", .def = .{ .steps = &.{.{ .cmd = 40108 }} } },
    .{ .name = "ItemSplitSelRight", .def = .{ .steps = &.{.{ .named = "_SWS_AWSPLITXFADELEFT" }} } },
    .{ .name = "JoinNotes", .def = .{ .steps = &.{ .{ .action = "SelectNotes" }, .{ .action = "JoinSelectedNotes" } } } },
    .{ .name = "JoinSelectedNotes", .def = .{ .steps = &.{.{ .cmd = 40456 }}, .midi_command = true } },
    // cursor pixel/grid moves
    .{ .name = "Left10Pix", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_MOVECUR10PIX_LEFT" }}, .prefix_repetition_count = true } },
    .{ .name = "Left40Pix", .def = .{ .steps = &.{.{ .action = "Left10Pix" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "LeftGridDivision", .def = .{ .steps = &.{.{ .cmd = 40646 }}, .prefix_repetition_count = true } },
    .{ .name = "LeftMidiGridDivision", .def = .{ .steps = &.{.{ .cmd = 40047 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "LoopEnd", .def = .{ .steps = &.{.{ .cmd = 40633 }} } },
    .{ .name = "LoopSelection", .def = .{ .steps = &.{.{ .action = "SetTimeSelectionToLoopSelection" }} } },
    .{ .name = "LoopStart", .def = .{ .steps = &.{.{ .cmd = 40632 }} } },
    .{ .name = "MakeFolder", .def = .{ .steps = &.{.{ .named = "_SWS_MAKEFOLDER" }} } },
    // track name search (the funcs themselves are skipped, refs stay)
    .{ .name = "MatchedTrackBackward", .def = .{ .steps = &.{ .{ .action = "MatchTrackNameBackward" }, .{ .action = "ScrollToSelectedTracks" } } } },
    .{ .name = "MatchedTrackForward", .def = .{ .steps = &.{ .{ .action = "MatchTrackNameForward" }, .{ .action = "ScrollToSelectedTracks" } } } },
    // midi CC / options
    .{ .name = "MidiCCMoveLeftByGrid", .def = .{ .steps = &.{.{ .cmd = 40672 }}, .prefix_repetition_count = true } },
    .{ .name = "MidiCCMoveLeftByPixel", .def = .{ .steps = &.{.{ .cmd = 40674 }}, .prefix_repetition_count = true } },
    .{ .name = "MidiCCMoveRightByGrid", .def = .{ .steps = &.{.{ .cmd = 40673 }}, .prefix_repetition_count = true } },
    .{ .name = "MidiCCMoveRightByPixel", .def = .{ .steps = &.{.{ .cmd = 40675 }}, .prefix_repetition_count = true } },
    .{ .name = "MidiLearnLastTouchedFxParam", .def = .{ .steps = &.{.{ .cmd = 41144 }} } },
    .{ .name = "MidiLoadNoteCCNames", .def = .{ .steps = &.{.{ .cmd = 40409 }} } },
    .{ .name = "MidiOptionAllowAllMediaItemsEditableInNotationView", .def = .{ .steps = &.{.{ .cmd = 41774 }} } },
    .{ .name = "MidiOptionAllowCCShapeInBankAndLSBLanes", .def = .{ .steps = &.{.{ .cmd = 42100 }} } },
    .{ .name = "MidiOptionAvoidAutomaticallySettingMIDIItemsFromOtherTracksEditable", .def = .{ .steps = &.{.{ .cmd = 40901 }} } },
    .{ .name = "MidiOptionEnableExtendingParentMediaItem", .def = .{ .steps = &.{.{ .cmd = 40817 }} } },
    .{ .name = "MidiOptionToggleAlwaysSnapNotesToTheLeftItSnap", .def = .{ .steps = &.{.{ .cmd = 40748 }} } },
    .{ .name = "MidiPaste", .def = .{ .steps = &.{.{ .cmd = 40011 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MidiSaveNoteCCNames", .def = .{ .steps = &.{.{ .cmd = 40410 }} } },
    .{ .name = "MidiTimeSelectionEnd", .def = .{ .steps = &.{.{ .cmd = 40881 }}, .midi_command = true } },
    .{ .name = "MidiTimeSelectionStart", .def = .{ .steps = &.{.{ .cmd = 40880 }}, .midi_command = true } },
    // midi editor views
    .{ .name = "DrumsView", .def = .{ .steps = &.{.{ .cmd = 40043 }}, .midi_command = true } },
    .{ .name = "EventView", .def = .{ .steps = &.{.{ .cmd = 40056 }}, .midi_command = true } },
    .{ .name = "NotationView", .def = .{ .steps = &.{.{ .cmd = 40954 }}, .midi_command = true } },
    .{ .name = "PianoRollView", .def = .{ .steps = &.{.{ .cmd = 40042 }}, .midi_command = true } },
    .{ .name = "MidiViewNoteRowsHideUnused", .def = .{ .steps = &.{.{ .cmd = 40453 }} } },
    .{ .name = "MidiViewNoteRowsHideUnusedAndUnnamed", .def = .{ .steps = &.{.{ .cmd = 40454 }} } },
    .{ .name = "MidiViewNoteRowsShowAll", .def = .{ .steps = &.{.{ .cmd = 40452 }} } },
    // midi zoom
    .{ .name = "MidiZoomContent", .def = .{ .steps = &.{.{ .cmd = 40466 }}, .midi_command = true } },
    .{ .name = "MidiZoomInHoriz", .def = .{ .steps = &.{.{ .cmd = 1012 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MidiZoomInVert", .def = .{ .steps = &.{.{ .cmd = 40111 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MidiZoomLoopSelection", .def = .{ .steps = &.{.{ .cmd = 40726 }}, .midi_command = true } },
    .{ .name = "MidiZoomOutHoriz", .def = .{ .steps = &.{.{ .cmd = 1011 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MidiZoomOutVert", .def = .{ .steps = &.{.{ .cmd = 40112 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MidiZoomTimeSelection", .def = .{ .steps = &.{ .{ .action = "SaveLoopSelection" }, .{ .action = "SetLoopSelectionToTimeSelection" }, .{ .action = "MidiZoomLoopSelection" }, .{ .action = "RestoreLoopSelection" } } } },
    .{ .name = "MinimizeTracks", .def = .{ .steps = &.{.{ .named = "_SWS_MINTRACKS" }} } },
    .{ .name = "MixerShowHideChildrenOfSelectedTrack", .def = .{ .steps = &.{.{ .cmd = 41665 }} } },
    .{ .name = "ModulateLastTouchedFxParam", .def = .{ .steps = &.{.{ .cmd = 41143 }} } },
    .{ .name = "MousePositionIgnoreSnap", .def = .{ .steps = &.{.{ .cmd = 40514 }} } },
    .{ .name = "MousePosition", .def = .{ .steps = &.{ .{ .action = "MousePositionIgnoreSnap" }, .{ .action = "SnappedPosition" } } } },
    .{ .name = "NextTransientInSelectedItems", .def = .{ .steps = &.{.{ .cmd = 40375 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevTransientInSelectedItems", .def = .{ .steps = &.{.{ .cmd = 40376 }}, .prefix_repetition_count = true } },
    // note nudging
    .{ .name = "MoveNoteDownOctave", .def = .{ .steps = &.{.{ .cmd = 40180 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteDownSemitone", .def = .{ .steps = &.{.{ .cmd = 40178 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteLeft", .def = .{ .steps = &.{.{ .cmd = 40183 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteLeftFine", .def = .{ .steps = &.{.{ .cmd = 40181 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteRight", .def = .{ .steps = &.{.{ .cmd = 40184 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteRightFine", .def = .{ .steps = &.{.{ .cmd = 40182 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteAndCursorRight", .def = .{ .steps = &.{ .{ .action = "RightMidiGridDivision" }, .{ .action = "MoveNoteRight" } }, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteAndCursorLeft", .def = .{ .steps = &.{ .{ .action = "LeftMidiGridDivision" }, .{ .action = "MoveNoteLeft" } }, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteUpOctave", .def = .{ .steps = &.{.{ .cmd = 40179 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveNoteUpSemitone", .def = .{ .steps = &.{.{ .cmd = 40177 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "MoveRedo", .def = .{ .steps = &.{.{ .named = "_SWS_EDITCURREDO" }}, .prefix_repetition_count = true } },
    .{ .name = "MoveSelectedItemLeftToEditCursor", .def = .{ .steps = &.{.{ .cmd = 41306 }} } },
    .{ .name = "MoveSelectedItemRightToEditCursor", .def = .{ .steps = &.{.{ .cmd = 41307 }} } },
    // FIXED: Lua had a recursive self-reference as the 2nd step (bug); dropped.
    .{ .name = "MoveToFirstItem", .def = .{ .steps = &.{.{ .action = "SelectFirstItemOnSelectedTracks" }} } },
    .{ .name = "MoveToMousePositionAndPlay", .def = .{ .steps = &.{ .{ .action = "MousePosition" }, .{ .action = "Play" } } } },
    .{ .name = "MoveUndo", .def = .{ .steps = &.{.{ .named = "_SWS_EDITCURUNDO" }}, .prefix_repetition_count = true } },
    .{ .name = "NewProjectTab", .def = .{ .steps = &.{.{ .cmd = 40859 }} } },
    // repeated motions
    .{ .name = "Next10Track", .def = .{ .steps = &.{.{ .action = "NextTrack" }}, .repetitions = 10, .prefix_repetition_count = true } },
    .{ .name = "Next4Beats", .def = .{ .steps = &.{.{ .action = "NextBeat" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "Next4Measures", .def = .{ .steps = &.{.{ .action = "NextMeasure" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "Next5Track", .def = .{ .steps = &.{.{ .action = "NextTrack" }}, .repetitions = 5, .prefix_repetition_count = true } },
    .{ .name = "NextBeat", .def = .{ .steps = &.{.{ .cmd = 40841 }} } },
    .{ .name = "NextEnvelope", .def = .{ .steps = &.{.{ .cmd = 41864 }}, .prefix_repetition_count = true } },
    .{ .name = "NextEnvelopePoint", .def = .{ .steps = &.{.{ .named = "_SWS_BRMOVEEDITTONEXTENV" }}, .prefix_repetition_count = true } },
    .{ .name = "NextFolderNear", .def = .{ .steps = &.{ .{ .named = "_SWS_SELNEARESTNEXTFOLDER" }, .{ .action = "ScrollToSelectedTracks" } }, .prefix_repetition_count = true } },
    .{ .name = "NextMarker", .def = .{ .steps = &.{.{ .cmd = 40173 }}, .prefix_repetition_count = true } },
    .{ .name = "NextMeasure", .def = .{ .steps = &.{.{ .cmd = 40839 }}, .prefix_repetition_count = true } },
    .{ .name = "NextNoteEnd", .def = .{ .steps = &.{ .{ .action = "SelectNextNote" }, .{ .action = "EventSelectionEnd" } }, .prefix_repetition_count = true } },
    .{ .name = "NextNoteSamePitchEnd", .def = .{ .steps = &.{ .{ .action = "SelectNextNoteSamePitch" }, .{ .action = "EventSelectionEnd" } }, .prefix_repetition_count = true } },
    .{ .name = "NextNoteSamePitchStart", .def = .{ .steps = &.{ .{ .action = "SelectNextNoteSamePitch" }, .{ .action = "EventSelectionStart" } }, .prefix_repetition_count = true } },
    .{ .name = "NextNoteStart", .def = .{ .steps = &.{ .{ .action = "SelectNextNote" }, .{ .action = "EventSelectionStart" } }, .prefix_repetition_count = true } },
    .{ .name = "NextRegion", .def = .{ .steps = &.{ .{ .action = "SetLoopRegionToNextRegion" }, .{ .action = "LoopStart" }, .{ .action = "SetTimeSelectionToLoopSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "NextTab", .def = .{ .steps = &.{.{ .cmd = 40861 }}, .prefix_repetition_count = true } },
    .{ .name = "NextTake", .def = .{ .steps = &.{.{ .cmd = 40125 }}, .prefix_repetition_count = true } },
    .{ .name = "NextTrack", .def = .{ .steps = &.{.{ .cmd = 40285 }}, .prefix_repetition_count = true } },
    .{ .name = "NextTrackMatchBackward", .def = .{ .steps = &.{ .{ .action = "RepeatTrackNameMatchBackward" }, .{ .action = "ScrollToSelectedTracks" } }, .prefix_repetition_count = true } },
    .{ .name = "NextTrackMatchForward", .def = .{ .steps = &.{ .{ .action = "RepeatTrackNameMatchForward" }, .{ .action = "ScrollToSelectedTracks" } }, .prefix_repetition_count = true } },
    .{ .name = "NextTransientInItem", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "NextTransientInSelectedItems" }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    // transients / stretch markers
    .{ .name = "CalculateTransientGuides", .def = .{ .steps = &.{.{ .cmd = 42028 }} } },
    .{ .name = "SplitItemAtTransients", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SPLIT_ITEMSATRANSIENTS" }} } },
    .{ .name = "ClearTransientGuides", .def = .{ .steps = &.{.{ .cmd = 42027 }} } },
    .{ .name = "InsertStretchMarker", .def = .{ .steps = &.{.{ .cmd = 41842 }} } },
    .{ .name = "DeleteStretchMarker", .def = .{ .steps = &.{.{ .cmd = 41859 }} } },
    .{ .name = "NextStretchMarker", .def = .{ .steps = &.{.{ .cmd = 41860 }} } },
    .{ .name = "PrevStretchMarker", .def = .{ .steps = &.{.{ .cmd = 41861 }} } },
    .{ .name = "IncreaseTransientDetectionThreshold", .def = .{ .steps = &.{.{ .cmd = 40218 }}, .prefix_repetition_count = true } },
    .{ .name = "DecreaseTransientDetectionThreshold", .def = .{ .steps = &.{.{ .cmd = 40219 }}, .prefix_repetition_count = true } },
    .{ .name = "IncreaseTransientDetectionSensitivity", .def = .{ .steps = &.{.{ .cmd = 41537 }}, .prefix_repetition_count = true } },
    .{ .name = "DecreaseTransientDetectionSensitivity", .def = .{ .steps = &.{.{ .cmd = 41536 }}, .prefix_repetition_count = true } },
    .{ .name = "AdjustTransientDetection", .def = .{ .steps = &.{.{ .cmd = 41208 }} } },
    .{ .name = "NoOp", .def = .{ .steps = &.{.{ .cmd = 65535 }} } },
    // pan / volume nudges
    .{ .name = "NudgeTrackPanLeft10Times", .def = .{ .steps = &.{.{ .action = "NudgeTrackPanLeft" }}, .repetitions = 10, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackPanLeft", .def = .{ .steps = &.{.{ .cmd = 40283 }}, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackPanRight10Times", .def = .{ .steps = &.{.{ .action = "NudgeTrackPanRight" }}, .repetitions = 10, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackPanRight", .def = .{ .steps = &.{.{ .cmd = 40284 }}, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeDownBy1", .def = .{ .steps = &.{.{ .action = "NudgeTrackVolumeDown" }}, .repetitions = 20, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeDownBy1Tenth", .def = .{ .steps = &.{.{ .action = "NudgeTrackVolumeDown" }}, .repetitions = 2, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeUp", .def = .{ .steps = &.{.{ .cmd = 40115 }}, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeUpBy1", .def = .{ .steps = &.{.{ .action = "NudgeTrackVolumeUp" }}, .repetitions = 20, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeUpBy1Tenth", .def = .{ .steps = &.{.{ .action = "NudgeTrackVolumeUp" }}, .repetitions = 2, .prefix_repetition_count = true } },
    .{ .name = "OnlySelectItemsCrossingTimeAndTrackSelection", .def = .{ .steps = &.{ .{ .action = "UnselectItems" }, .{ .action = "SelectItemsCrossingTimeAndTrackSelection" } } } },
    .{ .name = "OpenInMidiEditor", .def = .{ .steps = &.{ .{ .action = "SaveTrkScreenSet1" }, .{ .action = "ZoomItemSelection" }, .{ .cmd = 40153 } } } },
    .{ .name = "OpenProject", .def = .{ .steps = &.{.{ .cmd = 40025 }} } },
    // paste
    .{ .name = "PasteAbove", .def = .{ .steps = &.{ .{ .action = "PrevTrack" }, .{ .action = "Paste" } }, .prefix_repetition_count = true } },
    .{ .name = "PasteFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_SMART_PST_FXCHAIN" }}, .prefix_repetition_count = true } },
    .{ .name = "PasteItem", .def = .{ .steps = &.{.{ .cmd = 40058 }}, .prefix_repetition_count = true } },
    // extended_defaults: no Save/RestoreEditCursorPosition pre/post wrapping
    .{ .name = "Paste", .def = .{ .steps = &.{.{ .named = "_SWS_AWPASTE" }}, .prefix_repetition_count = true } },
    .{ .name = "Pause", .def = .{ .steps = &.{.{ .cmd = 1008 }} } },
    // pitch
    .{ .name = "PitchDown", .def = .{ .steps = &.{.{ .cmd = 40050 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchDown7", .def = .{ .steps = &.{.{ .action = "PitchDown" }}, .repetitions = 7, .prefix_repetition_count = true } },
    .{ .name = "PitchDownOctave", .def = .{ .steps = &.{.{ .cmd = 40188 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchUp", .def = .{ .steps = &.{.{ .cmd = 40049 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchUp7", .def = .{ .steps = &.{.{ .action = "PitchUp" }}, .repetitions = 7, .prefix_repetition_count = true } },
    .{ .name = "PitchUpOctave", .def = .{ .steps = &.{.{ .cmd = 40187 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchCursorDownOctave", .def = .{ .steps = &.{.{ .cmd = 40188 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchCursorUpOctave", .def = .{ .steps = &.{.{ .cmd = 40187 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchCursorDown", .def = .{ .steps = &.{.{ .cmd = 40050 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "PitchCursorUp", .def = .{ .steps = &.{.{ .cmd = 40049 }}, .midi_command = true, .prefix_repetition_count = true } },
    // transport
    .{ .name = "Play", .def = .{ .steps = &.{.{ .cmd = 1007 }} } },
    .{ .name = "PlayAndLoop", .def = .{ .steps = &.{ .{ .action = "SetLoopSelectionToTimeSelection" }, .{ .action = "SaveEditCursorPosition" }, .{ .action = "LoopStart" }, .{ .action = "Play" }, .{ .action = "RestoreEditCursorPosition" } }, .set_time_selection = true } },
    .{ .name = "PlayFromMousePosition", .def = .{ .steps = &.{.{ .named = "_BR_PLAY_MOUSECURSOR" }} } },
    .{ .name = "PlayFromTimeSelectionStart", .def = .{ .steps = &.{ .{ .action = "SaveEditCursorPosition" }, .{ .action = "TimeSelectionStart" }, .{ .action = "Play" }, .{ .action = "RestoreEditCursorPosition" } } } },
    // metaCommand: macro playback is handled by the state machine, not steps
    .{ .name = "PlayMacro", .def = .{ .register_action = true, .prefix_repetition_count = true } },
    .{ .name = "PlayPositionIgnoreSnap", .def = .{ .steps = &.{.{ .cmd = 40434 }} } },
    .{ .name = "PlayPosition", .def = .{ .steps = &.{ .{ .action = "PlayPositionIgnoreSnap" }, .{ .action = "SnappedPosition" } } } },
    .{ .name = "Prev10Track", .def = .{ .steps = &.{.{ .action = "PrevTrack" }}, .repetitions = 10, .prefix_repetition_count = true } },
    .{ .name = "Prev4Beats", .def = .{ .steps = &.{.{ .action = "PrevBeat" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "Prev4Measures", .def = .{ .steps = &.{.{ .action = "PrevMeasure" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "Prev5Track", .def = .{ .steps = &.{.{ .action = "PrevTrack" }}, .repetitions = 5, .prefix_repetition_count = true } },
    .{ .name = "PrevBeat", .def = .{ .steps = &.{.{ .cmd = 40842 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevEnvelope", .def = .{ .steps = &.{.{ .cmd = 41863 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevEnvelopePoint", .def = .{ .steps = &.{.{ .named = "_SWS_BRMOVEEDITTOPREVENV" }}, .prefix_repetition_count = true } },
    // extended_defaults uses the _BR_ENV_SEL_* variants here
    .{ .name = "SelNextEnvelopePoint", .def = .{ .steps = &.{.{ .named = "_BR_ENV_SEL_NEXT_POINT" }}, .prefix_repetition_count = true } },
    .{ .name = "SelPrevEnvelopePoint", .def = .{ .steps = &.{.{ .named = "_BR_ENV_SEL_PREV_POINT" }}, .prefix_repetition_count = true } },
    .{ .name = "AddNextEnvelopePointSel", .def = .{ .steps = &.{.{ .named = "_SWS_BRMOVEEDITTONEXTENVADDSELL" }}, .prefix_repetition_count = true } },
    // FIXED: Lua copy/paste bug pointed this at the ...TONEXTENVADDSELL command
    .{ .name = "AddPrevEnvelopePointSel", .def = .{ .steps = &.{.{ .named = "_SWS_BRMOVEEDITTOPREVENVADDSELL" }}, .prefix_repetition_count = true } },
    .{ .name = "PrevFolderNear", .def = .{ .steps = &.{ .{ .named = "_SWS_SELNEARESTPREVFOLDER" }, .{ .action = "ScrollToSelectedTracks" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevMarker", .def = .{ .steps = &.{.{ .cmd = 40172 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevMeasure", .def = .{ .steps = &.{.{ .cmd = 40840 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevNoteEnd", .def = .{ .steps = &.{ .{ .action = "SelectPrevNote" }, .{ .action = "PitchCursorToSelectedNote" }, .{ .action = "EventSelectionEnd" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevNoteSamePitchEnd", .def = .{ .steps = &.{ .{ .action = "SelectPrevNoteSamePitch" }, .{ .action = "EventSelectionEnd" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevNoteSamePitchStart", .def = .{ .steps = &.{ .{ .action = "SelectPrevNoteSamePitch" }, .{ .action = "EventSelectionStart" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevNoteStart", .def = .{ .steps = &.{ .{ .action = "SelectPrevNote" }, .{ .action = "EventSelectionStart" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevRegion", .def = .{ .steps = &.{ .{ .action = "SetLoopRegionToPrevRegion" }, .{ .action = "LoopStart" }, .{ .action = "SetTimeSelectionToLoopSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevTab", .def = .{ .steps = &.{.{ .cmd = 40862 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevTake", .def = .{ .steps = &.{.{ .cmd = 40126 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevTrack", .def = .{ .steps = &.{.{ .cmd = 40286 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevTransientInItem", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "PrevTransientInSelectedItems" }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "NextTransientInItemMinusFadeTime", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "NextTransientInSelectedItemsMinusFadeTime" }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevTransientInItemMinusFadeTime", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "PrevTransientInSelectedItemsMinusFadeTime" }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "NextTransientInSelectedItemsMinusFadeTime", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_MOVECURNEXT_TRANSMINUSFADE" }} } },
    .{ .name = "PrevTransientInSelectedItemsMinusFadeTime", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_MOVECURPREV_TRANSMINUSFADE" }} } },
    .{ .name = "Quantize", .def = .{ .steps = &.{.{ .cmd = 40009 }}, .midi_command = true } },
    // OMITTED: RecallMark — lib.marks.recall does not exist in the Lua source
    // (broken nil reference); port a native recall fn alongside Mark instead.
    .{ .name = "RecordConditional", .def = .{ .steps = &.{ .{ .action = "Stop" }, .{ .action = "ToggleRecordConditional" } } } },
    // metaCommand: macro recording handled by the state machine, not steps
    .{ .name = "RecordMacro", .def = .{ .register_action = true, .register_optional = true } },
    .{ .name = "RecordOrStop", .def = .{ .steps = &.{.{ .named = "_SWS_RECTOGGLE" }} } },
    .{ .name = "Record", .def = .{ .steps = &.{ .{ .action = "SaveEditCursorPosition" }, .{ .action = "TimeSelectionStart" }, .{ .action = "RecordConditional" }, .{ .action = "RestoreEditCursorPosition" } }, .set_time_selection = true } },
    .{ .name = "Redo", .def = .{ .steps = &.{.{ .cmd = 40030 }}, .prefix_repetition_count = true } },
    .{ .name = "RegionSelectItems", .def = .{ .steps = &.{.{ .cmd = 40717 }} } },
    .{ .name = "RemoveMarker", .def = .{ .steps = &.{.{ .cmd = 40613 }} } },
    .{ .name = "RemoveRegion", .def = .{ .steps = &.{.{ .cmd = 40615 }} } },
    .{ .name = "RemoveTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40635 }} } },
    .{ .name = "RemoveTrack", .def = .{ .steps = &.{.{ .cmd = 40005 }} } },
    .{ .name = "RenameTrack", .def = .{ .steps = &.{.{ .cmd = 40696 }} } },
    .{ .name = "RenameTakeSourceFile", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_RENMTAKEANDSOURCE" }} } },
    .{ .name = "RenameTake", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_RENMTAKE" }} } },
    .{ .name = "RenameTakeAndSourceFile", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_RENMTAKEANDSOURCE" }} } },
    .{ .name = "RenderProject", .def = .{ .steps = &.{.{ .cmd = 40015 }} } },
    .{ .name = "RenderProjectWithLastSetting", .def = .{ .steps = &.{.{ .cmd = 41824 }} } },
    .{ .name = "RenderTrack", .def = .{ .steps = &.{.{ .named = "_SWS_AWRENDERSTEREOSMART" }} } },
    // metaCommand: dot-repeat handled by the state machine, not steps
    .{ .name = "RepeatLastCommand", .def = .{ .prefix_repetition_count = true } },
    .{ .name = "ResetAllControlSurfaceDevices", .def = .{ .steps = &.{.{ .cmd = 42348 }} } },
    .{ .name = "ResetAllMidiDevices", .def = .{ .steps = &.{.{ .cmd = 41175 }} } },
    .{ .name = "ResetControlDevices", .def = .{ .steps = &.{ .{ .action = "ResetAllMidiDevices" }, .{ .action = "ResetAllControlSurfaceDevices" } } } },
    .{ .name = "ResetSelection", .def = .{ .steps = &.{ .{ .action = "SelectOnlyCurrentTrack" }, .{ .action = "UnselectItems" }, .{ .action = "UnselectEnvelopePoints" }, .{ .action = "UnselectAllEvents" } } } },
    .{ .name = "Reset", .def = .{ .steps = &.{ .{ .action = "Stop" }, .{ .action = "SetModeNormal" }, .{ .action = "SetRecordModeNormal" }, .{ .action = "ResetSelection" }, .{ .action = "RemoveTimeSelection" } } } },
    .{ .name = "ResetSelectionMidi", .def = .{ .steps = &.{ .{ .action = "UnselectEnvelopePoints" }, .{ .action = "UnselectAllEvents" } } } },
    .{ .name = "ResetMidi", .def = .{ .steps = &.{ .{ .action = "Stop" }, .{ .action = "SetModeNormal" }, .{ .action = "ResetSelectionMidi" }, .{ .action = "RemoveTimeSelection" } } } },
    .{ .name = "ResetTrackToNormal", .def = .{ .steps = &.{ .{ .action = "UnarmSelectedTracks" }, .{ .action = "UnarmAllEnvelopes" }, .{ .action = "SetAutomationModeTrimRead" } } } },
    // save/restore slots
    .{ .name = "RestoreEditCursorPosition", .def = .{ .steps = &.{.{ .named = "_BR_RESTORE_CURSOR_POS_SLOT_16" }} } },
    .{ .name = "RestoreItemSelection", .def = .{ .steps = &.{.{ .named = "_SWS_RESTALLSELITEMS1" }} } },
    .{ .name = "RestoreLastItemSelection", .def = .{ .steps = &.{.{ .named = "_SWS_RESTLASTSEL" }} } },
    .{ .name = "RestoreLoopSelection", .def = .{ .steps = &.{.{ .named = "_SWS_RESTLOOP5" }} } },
    .{ .name = "RestoreTimeSelection", .def = .{ .steps = &.{.{ .named = "_SWS_RESTTIME5" }} } },
    .{ .name = "RestoreTrackSelection", .def = .{ .steps = &.{.{ .named = "_SWS_TOGSAVESEL" }} } },
    .{ .name = "Right10Pix", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_MOVECUR10PIX_RIGHT" }}, .prefix_repetition_count = true } },
    .{ .name = "Right40Pix", .def = .{ .steps = &.{.{ .action = "Right10Pix" }}, .repetitions = 4, .prefix_repetition_count = true } },
    .{ .name = "RightGridDivision", .def = .{ .steps = &.{.{ .cmd = 40647 }}, .prefix_repetition_count = true } },
    .{ .name = "RightMidiGridDivision", .def = .{ .steps = &.{.{ .cmd = 40048 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "SaveEditCursorPosition", .def = .{ .steps = &.{.{ .named = "_BR_SAVE_CURSOR_POS_SLOT_16" }} } },
    .{ .name = "SaveItemSelection", .def = .{ .steps = &.{.{ .named = "_SWS_SAVEALLSELITEMS1" }} } },
    .{ .name = "SaveLoopSelection", .def = .{ .steps = &.{.{ .named = "_SWS_SAVELOOP5" }} } },
    .{ .name = "SaveProject", .def = .{ .steps = &.{.{ .cmd = 40026 }} } },
    .{ .name = "SaveProjectWithNewVersion", .def = .{ .steps = &.{.{ .cmd = 41895 }} } },
    .{ .name = "SaveTimeSelection", .def = .{ .steps = &.{.{ .named = "_SWS_SAVETIME5" }} } },
    .{ .name = "SaveTrackSelection", .def = .{ .steps = &.{.{ .named = "_SWS_SAVESEL" }} } },
    // scrolling
    .{ .name = "ScrollToPlayPosition", .def = .{ .steps = &.{.{ .cmd = 40150 }} } },
    .{ .name = "ScrollToEditCursor", .def = .{ .steps = &.{.{ .named = "_SWS_HSCROLL10" }} } },
    .{ .name = "ScrollToSelectedTracks", .def = .{ .steps = &.{.{ .cmd = 40913 }} } },
    // extended_defaults: also scrolls selected tracks into view
    .{ .name = "CenterCursor", .def = .{ .steps = &.{ .{ .action = "ScrollToSelectedTracks" }, .{ .named = "_SWS_HSCROLL50" } } } },
    // selection
    .{ .name = "SelectAllItems", .def = .{ .steps = &.{.{ .cmd = 40182 }} } },
    .{ .name = "SelectAllNotesAtPitch", .def = .{ .steps = &.{.{ .cmd = 41746 }}, .midi_command = true } },
    .{ .name = "SelectAllTracks", .def = .{ .steps = &.{.{ .cmd = 40296 }} } },
    .{ .name = "SelectedItems", .def = .{ .steps = &.{ .{ .action = "RemoveTimeSelection" }, .{ .named = "_SWS_SAFETIMESEL" } } } },
    .{ .name = "SelectedNotes", .def = .{ .steps = &.{.{ .cmd = 40752 }}, .midi_command = true } },
    .{ .name = "SelectEventsInTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40876 }}, .midi_command = true } },
    .{ .name = "SelectFirstItemOnSelectedTracks", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELFIRSTITEMSOFTRACKS" }} } },
    .{ .name = "SelectFirstOfSelectedTracks", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELFIRSTOFSELTRAX" }} } },
    .{ .name = "SelectFolderChildren", .def = .{ .steps = &.{.{ .named = "_SWS_SELCHILDREN" }} } },
    .{ .name = "SelectFolderParent", .def = .{ .steps = &.{.{ .named = "_SWS_SELPARENTS" }} } },
    .{ .name = "SelectFolder", .def = .{ .steps = &.{.{ .named = "_SWS_SELCHILDREN2" }} } },
    .{ .name = "Selection", .def = .{ .steps = &.{.{ .action = "NoOp" }} } }, // placeholder selector
    .{ .name = "SelectItemsAndSplit", .def = .{ .steps = &.{ .{ .action = "OnlySelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "SplitItemsAtTimeSelection" } } } },
    .{ .name = "SelectItemsCrossingTimeAndTrackSelection", .def = .{ .steps = &.{.{ .cmd = 40718 }} } },
    .{ .name = "SelectItemsInGroups", .def = .{ .steps = &.{.{ .cmd = 40034 }} } },
    .{ .name = "SelectItemsOnTrack", .def = .{ .steps = &.{.{ .cmd = 40421 }} } },
    .{ .name = "SelectItems", .def = .{ .steps = &.{.{ .action = "SelectItemsCrossingTimeAndTrackSelection" }} } },
    .{ .name = "SelectItemsUnderEditCursor", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELITEMSUNDEDCURSELTX" }} } },
    .{ .name = "SelectLastOfSelectedTracks", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELLASTOFSELTRAX" }} } },
    .{ .name = "SelectLastTouchedTrack", .def = .{ .steps = &.{.{ .cmd = 40505 }} } },
    .{ .name = "SelectNearestNote", .def = .{ .steps = &.{.{ .cmd = 40425 }}, .midi_command = true } },
    .{ .name = "SelectNextNote", .def = .{ .steps = &.{ .{ .cmd = 40413 }, .{ .action = "PitchCursorToSelectedNote" } }, .midi_command = true } },
    .{ .name = "SelectNextNoteSamePitch", .def = .{ .steps = &.{.{ .cmd = 40428 }}, .midi_command = true } },
    .{ .name = "SelectNoteClosestToEditCursor", .def = .{ .steps = &.{.{ .cmd = 40426 }}, .midi_command = true } },
    .{ .name = "SelectNotes", .def = .{ .steps = &.{.{ .action = "SelectNotesStartingInTimeSelection" }} } },
    .{ .name = "SelectNotesStartingInTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40877 }}, .midi_command = true } },
    .{ .name = "SelectOnlyFoldersChildren", .def = .{ .steps = &.{.{ .named = "_SWS_SELCHILDREN" }} } },
    .{ .name = "SelectPrevNote", .def = .{ .steps = &.{ .{ .cmd = 40414 }, .{ .action = "PitchCursorToSelectedNote" } }, .midi_command = true } },
    .{ .name = "SelectPrevNoteSamePitch", .def = .{ .steps = &.{.{ .cmd = 40427 }}, .midi_command = true } },
    // pure flag entry: track selection handled by the state machine
    .{ .name = "SelectTracks", .def = .{ .set_track_selection = true } },
    .{ .name = "ToggleItemDefaultFadeInAndOut", .def = .{ .steps = &.{.{ .cmd = 41194 }} } },
    // automation modes
    .{ .name = "SetAutomationModeLatch", .def = .{ .steps = &.{.{ .cmd = 40404 }} } },
    .{ .name = "SetAutomationModeLatchAndArm", .def = .{ .steps = &.{ .{ .action = "SetAutomationModeLatch" }, .{ .action = "ArmAllEnvelopes" } } } },
    .{ .name = "SetAutomationModeLatchPreview", .def = .{ .steps = &.{.{ .cmd = 42023 }} } },
    .{ .name = "SetAutomationModeRead", .def = .{ .steps = &.{.{ .cmd = 40401 }} } },
    .{ .name = "SetAutomationModeTouch", .def = .{ .steps = &.{.{ .cmd = 40402 }} } },
    .{ .name = "SetAutomationModeTrimRead", .def = .{ .steps = &.{.{ .cmd = 40400 }} } },
    .{ .name = "SetRippleEditAllTracks", .def = .{ .steps = &.{.{ .cmd = 40311 }} } },
    .{ .name = "SetRippleEditOff", .def = .{ .steps = &.{.{ .cmd = 40309 }} } },
    .{ .name = "SetRippleEditPerTrack", .def = .{ .steps = &.{.{ .cmd = 40310 }} } },
    .{ .name = "DuplicateTimeline", .def = .{ .steps = &.{ .{ .action = "SaveTrackSelection" }, .{ .action = "SelectAllTracks" }, .{ .action = "CopyItems" }, .{ .action = "TimeSelectionEnd" }, .{ .action = "SetRippleEditAllTracks" }, .{ .action = "FirstTrackWithItem" }, .{ .action = "Paste" }, .{ .action = "SetRippleEditOff" }, .{ .action = "RestoreTrackSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "ExplodeTakesInPlace", .def = .{ .steps = &.{.{ .cmd = 40642 }} } },
    .{ .name = "ExplodeTakesInOrder", .def = .{ .steps = &.{.{ .cmd = 40643 }} } },
    .{ .name = "ToggleBetweenReadAndTouchAutomationMode", .def = .{ .steps = &.{.{ .cmd = 41109 }} } },
    .{ .name = "QuantizeItems", .def = .{ .steps = &.{.{ .cmd = 40316 }} } },
    .{ .name = "ExplodeTakesInAcrossTracks", .def = .{ .steps = &.{.{ .cmd = 40224 }} } },
    .{ .name = "SetAutomationModeWrite", .def = .{ .steps = &.{.{ .cmd = 40403 }} } },
    .{ .name = "OpenConsole", .def = .{ .steps = &.{.{ .named = "_SWSCONSOLE" }} } },
    .{ .name = "SetFirstSelectedTrackAsLastTouchedTrack", .def = .{ .steps = &.{.{ .cmd = 40914 }} } },
    .{ .name = "SetGlobalAutomationModeLatch", .def = .{ .steps = &.{.{ .cmd = 40881 }} } },
    .{ .name = "SetGlobalAutomationModeLatchPreview", .def = .{ .steps = &.{.{ .cmd = 42022 }} } },
    .{ .name = "SetGlobalAutomationModeOff", .def = .{ .steps = &.{.{ .cmd = 40876 }} } },
    .{ .name = "SetGlobalAutomationModeRead", .def = .{ .steps = &.{.{ .cmd = 40879 }} } },
    .{ .name = "SetGlobalAutomationModeTouch", .def = .{ .steps = &.{.{ .cmd = 40880 }} } },
    .{ .name = "SetGlobalAutomationModeTrimRead", .def = .{ .steps = &.{.{ .cmd = 40878 }} } },
    .{ .name = "SetGlobalAutomationModeWrite", .def = .{ .steps = &.{.{ .cmd = 40882 }} } },
    .{ .name = "SetItemFadeBoundaries", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "UnselectItems" }, .{ .action = "SelectItemsCrossingTimeAndTrackSelection" }, .{ .action = "SetSelectedItemFadeBoundaries" }, .{ .action = "RestoreItemSelection" } } } },
    // timebase
    .{ .name = "SetItemsTimebaseToBeatsPosLengthAndRate", .def = .{ .steps = &.{.{ .named = "_SWS_AWITEMTBASEBEATALL" }} } },
    .{ .name = "ViewTakeEnvelopes", .def = .{ .steps = &.{.{ .cmd = 41974 }} } },
    .{ .name = "SetItemsTimebaseToBeatsPos", .def = .{ .steps = &.{.{ .named = "_SWS_AWITEMTBASEBEATPOS" }} } },
    .{ .name = "SetItemsTimebaseToDefault", .def = .{ .steps = &.{.{ .named = "_SWS_AWITEMTBASEPROJ" }} } },
    .{ .name = "SetItemsTimebaseToTime", .def = .{ .steps = &.{.{ .named = "_SWS_AWITEMTBASETIME" }} } },
    .{ .name = "SetLoopEnd", .def = .{ .steps = &.{.{ .cmd = 40223 }} } },
    .{ .name = "SetLoopRegionToNextRegion", .def = .{ .steps = &.{.{ .named = "_SWS_SELNEXTREG" }} } },
    .{ .name = "SetLoopRegionToPrevRegion", .def = .{ .steps = &.{.{ .named = "_SWS_SELPREVREG" }} } },
    .{ .name = "SetLoopSelectionToTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40622 }} } },
    .{ .name = "SetLoopStart", .def = .{ .steps = &.{.{ .cmd = 40222 }} } },
    .{ .name = "PasteItemFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_COPYFXCHAIN9" }}, .prefix_repetition_count = true } },
    // SetModeNormal/SetModeVisualTimeline/SetModeVisualTrack live in lib_state.zig
    .{ .name = "ClearTimelineSelectionAndSetModeVisualTimeline", .def = .{ .steps = &.{ .{ .action = "ClearSelectedTimeline" }, .{ .action = "SetModeVisualTimeline" } } } },
    // OMITTED: SetModeRecord — lib.state.setModeRecord does not exist in the
    // Lua source (broken nil reference); needs a native fn if ever wanted.
    .{ .name = "SetProjectTimebaseToBeatsPosLengthAndRate", .def = .{ .steps = &.{.{ .named = "_SWS_AWTBASEBEATALL" }} } },
    .{ .name = "SetProjectTimebaseToBeatsPos", .def = .{ .steps = &.{.{ .named = "_SWS_AWTBASEBEATPOS" }} } },
    .{ .name = "SetProjectTimebaseToTime", .def = .{ .steps = &.{.{ .named = "_SWS_AWTBASETIME" }} } },
    // record settings
    .{ .name = "SetRecordInput", .def = .{ .steps = &.{.{ .cmd = 40496 }} } },
    .{ .name = "SetRecordMidiOutput", .def = .{ .steps = &.{.{ .cmd = 40500 }} } },
    .{ .name = "SetRecordMidiOverdub", .def = .{ .steps = &.{.{ .cmd = 40503 }} } },
    .{ .name = "SetRecordMidiReplace", .def = .{ .steps = &.{.{ .cmd = 40504 }} } },
    .{ .name = "SetRecordMidiTouchReplace", .def = .{ .steps = &.{.{ .cmd = 40852 }} } },
    .{ .name = "SetRecordModeNormal", .def = .{ .steps = &.{.{ .cmd = 40252 }} } },
    .{ .name = "SetRecordMonitorOnly", .def = .{ .steps = &.{.{ .cmd = 40498 }} } },
    .{ .name = "SetSelectedItemFadeBoundaries", .def = .{ .steps = &.{.{ .named = "_SWS_AWFADESEL" }} } },
    .{ .name = "SetTimeSelectionEnd", .def = .{ .steps = &.{.{ .cmd = 40626 }} } },
    .{ .name = "SetTimeSelectionStart", .def = .{ .steps = &.{.{ .cmd = 40625 }} } },
    .{ .name = "SetTimeSelectionToLoopSelection", .def = .{ .steps = &.{.{ .cmd = 40623 }} } },
    .{ .name = "SetTrackMidiAllChannels", .def = .{ .steps = &.{.{ .named = "_S&M_MIDI_INPUT_ALL_CH" }} } },
    .{ .name = "TimeSelectionShiftedLeft", .def = .{ .steps = &.{.{ .cmd = 40037 }} } },
    .{ .name = "TimeSelectionShiftedRight", .def = .{ .steps = &.{.{ .cmd = 40038 }} } },
    // windows / views
    .{ .name = "ShowActionList", .def = .{ .steps = &.{.{ .cmd = 40605 }} } },
    .{ .name = "ShowMidiActionList", .def = .{ .steps = &.{.{ .cmd = 40420 }}, .midi_command = true } },
    .{ .name = "ShowNextFx", .def = .{ .steps = &.{.{ .named = "_S&M_WNONLY2" }}, .prefix_repetition_count = true } },
    .{ .name = "ShowPreferences", .def = .{ .steps = &.{.{ .cmd = 40016 }} } },
    .{ .name = "ShowPrevFx", .def = .{ .steps = &.{.{ .named = "_S&M_WNONLY1" }}, .prefix_repetition_count = true } },
    .{ .name = "ShowProjectSettings", .def = .{ .steps = &.{.{ .cmd = 40021 }} } },
    .{ .name = "RoutingMatrix", .def = .{ .steps = &.{.{ .cmd = 40251 }} } },
    .{ .name = "ShowTrackFreezeDetails", .def = .{ .steps = &.{.{ .cmd = 41654 }} } },
    .{ .name = "ToggleShowTrackManager", .def = .{ .steps = &.{.{ .cmd = 40906 }} } },
    .{ .name = "ToggleShowTrackRouting", .def = .{ .steps = &.{.{ .cmd = 40293 }} } },
    .{ .name = "ToggleShowWiringDiagram", .def = .{ .steps = &.{.{ .cmd = 42031 }} } },
    // snapshots
    .{ .name = "AddAndNameSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_NEWEDIT" }} } },
    .{ .name = "CopyCurrentSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_COPY" }} } },
    .{ .name = "PasteSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_PASTE" }} } },
    .{ .name = "DeleteCurrentSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_DELCUR" }} } },
    .{ .name = "DeleteTracksFromCurrentSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_DEL" }} } },
    .{ .name = "ToggleSnapshotsWindow", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_OPEN" }} } },
    .{ .name = "RecallCurrentSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET" }} } },
    .{ .name = "RecallNextSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET_NEXT" }}, .prefix_repetition_count = true } },
    .{ .name = "RecallPrevSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET_PREVIOUS" }}, .prefix_repetition_count = true } },
    .{ .name = "RecallSnapshot1", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET1" }} } },
    .{ .name = "RecallSnapshot2", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET2" }} } },
    .{ .name = "RecallSnapshot3", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET3" }} } },
    .{ .name = "RecallSnapshot4", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET4" }} } },
    .{ .name = "RecallSnapshot5", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET5" }} } },
    .{ .name = "RecallSnapshot6", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET6" }} } },
    .{ .name = "RecallSnapshot7", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET7" }} } },
    .{ .name = "RecallSnapshot8", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET8" }} } },
    .{ .name = "RecallSnapshot9", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET9" }} } },
    .{ .name = "SaveTracksToCurrentSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_SAVE" }} } },
    .{ .name = "DeleteAllSnapshots", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_DELALL" }} } },
    // splitting
    .{ .name = "SplitItemsAtEditCursor", .def = .{ .steps = &.{ .{ .action = "UnselectItems" }, .{ .action = "SelectItemsUnderEditCursor" }, .{ .action = "SplitItemsUnderEditCursor" }, .{ .action = "UnselectItems" } } } },
    .{ .name = "SplitItemsUnderEditCursor", .def = .{ .steps = &.{.{ .cmd = 40757 }} } },
    .{ .name = "StartOfSel", .def = .{ .steps = &.{.{ .cmd = 40440 }}, .midi_command = true } },
    .{ .name = "StartOfSelectedItems", .def = .{ .steps = &.{.{ .cmd = 41173 }} } },
    .{ .name = "StartStop", .def = .{ .steps = &.{.{ .cmd = 40044 }} } },
    .{ .name = "Stop", .def = .{ .steps = &.{.{ .cmd = 1016 }} } },
    .{ .name = "StopAndSaveRecordedMedia", .def = .{ .steps = &.{.{ .cmd = 40667 }} } },
    // metaCommand: ends macro recording in the state machine, not steps
    .{ .name = "StopRecordMacro", .def = .{} },
    // SwitchTimelineSelectionSide lives in lib_state.zig
    .{ .name = "TapTempo", .def = .{ .steps = &.{.{ .cmd = 1134 }} } },
    .{ .name = "TimeSelectionEnd", .def = .{ .steps = &.{.{ .cmd = 40631 }} } },
    .{ .name = "InsertTrackFromTemplateSlot1", .def = .{ .steps = &.{.{ .named = "_S&M_ADD_TRTEMPLATE1" }} } },
    .{ .name = "InsertTrackFromTemplateSlot2", .def = .{ .steps = &.{.{ .named = "_S&M_ADD_TRTEMPLATE2" }} } },
    .{ .name = "InsertTrackFromTemplateSlot3", .def = .{ .steps = &.{.{ .named = "_S&M_ADD_TRTEMPLATE3" }} } },
    .{ .name = "InsertTrackFromTemplateSlot4", .def = .{ .steps = &.{.{ .named = "_S&M_ADD_TRTEMPLATE4" }} } },
    .{ .name = "CreateNewSnapshotWithTracks", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_NEWSEL" }} } },
    .{ .name = "RecallPreviousSnapshot", .def = .{ .steps = &.{.{ .named = "_SWSSNAPSHOT_GET_PREVIOUS" }} } },
    .{ .name = "SaveTrackAsTemplate", .def = .{ .steps = &.{.{ .cmd = 40392 }} } },
    .{ .name = "TimeSelection", .def = .{ .steps = &.{.{ .action = "NoOp" }} } }, // placeholder selector
    .{ .name = "TimeSelectionStart", .def = .{ .steps = &.{.{ .cmd = 40630 }} } },
    // toggles
    .{ .name = "ToggleArmAllEnvelopes", .def = .{ .steps = &.{.{ .named = "_S&M_TGLARMALLENVS" }} } },
    .{ .name = "ToggleArmEnvelope", .def = .{ .steps = &.{.{ .cmd = 40863 }} } },
    .{ .name = "ToggleAutoCrossfade", .def = .{ .steps = &.{.{ .cmd = 40041 }} } },
    .{ .name = "ToggleCountInBeforePlayback", .def = .{ .steps = &.{.{ .named = "_SWS_AWCOUNTPLAYTOG" }} } },
    .{ .name = "ToggleCountInBeforeRec", .def = .{ .steps = &.{.{ .named = "_SWS_AWCOUNTRECTOG" }} } },
    .{ .name = "ToggleEnvelopePointsMoveWithItems", .def = .{ .steps = &.{.{ .cmd = 40070 }} } },
    .{ .name = "ToggleFloatingWindows", .def = .{ .steps = &.{.{ .cmd = 41074 }} } },
    .{ .name = "ToggleFxBypass", .def = .{ .steps = &.{.{ .cmd = 8 }} } },
    .{ .name = "ToggleTakeFxBypass", .def = .{ .steps = &.{.{ .named = "_S&M_TGL_TAKEFX_BYP" }} } },
    .{ .name = "ToggleEnvelopeBypass", .def = .{ .steps = &.{.{ .cmd = 40883 }} } },
    .{ .name = "ToggleLoop", .def = .{ .steps = &.{.{ .cmd = 1068 }} } },
    .{ .name = "ToggleLoopSelectionFollowsTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40621 }} } },
    .{ .name = "ToggleMetronome", .def = .{ .steps = &.{.{ .cmd = 40364 }} } },
    .{ .name = "ToggleMidiEditorUsesMainGridDivision", .def = .{ .steps = &.{.{ .cmd = 42010 }} } },
    .{ .name = "ToggleMidiSnap", .def = .{ .steps = &.{.{ .cmd = 1014 }}, .midi_command = true } },
    .{ .name = "ToggleMute", .def = .{ .steps = &.{.{ .cmd = 6 }} } },
    .{ .name = "ToggleMuteItem", .def = .{ .steps = &.{.{ .cmd = 40175 }} } },
    .{ .name = "TogglePanEnvelope", .def = .{ .steps = &.{.{ .cmd = 40407 }} } },
    .{ .name = "TogglePlaybackAutoScroll", .def = .{ .steps = &.{.{ .cmd = 40036 }} } },
    .{ .name = "TogglePlaybackPreroll", .def = .{ .steps = &.{.{ .cmd = 41818 }} } },
    .{ .name = "ToggleRecord", .def = .{ .steps = &.{ .{ .action = "SetRecordModeNormal" }, .{ .cmd = 1013 } } } },
    .{ .name = "StopRecord", .def = .{ .steps = &.{ .{ .action = "StartStop" }, .{ .action = "SetModeNormal" } } } },
    .{ .name = "ToggleRecordConditional", .def = .{ .steps = &.{.{ .named = "_SWS_AWRECORDCOND" }} } },
    .{ .name = "ToggleRecordingAutoScroll", .def = .{ .steps = &.{.{ .cmd = 40262 }} } },
    .{ .name = "ToggleRecordingPreroll", .def = .{ .steps = &.{.{ .cmd = 41819 }} } },
    .{ .name = "ToggleRecordToTapeMode", .def = .{ .steps = &.{.{ .cmd = 41186 }} } },
    .{ .name = "ToggleShowRegionMarkerManager", .def = .{ .steps = &.{.{ .cmd = 40326 }} } },
    .{ .name = "RegionPlaylist", .def = .{ .steps = &.{.{ .named = "_S&M_SHOW_RGN_PLAYLIST" }} } },
    .{ .name = "ToggleShowAllEnvelope", .def = .{ .steps = &.{.{ .cmd = 41151 }} } },
    .{ .name = "ToggleShowAllEnvelopeGlobal", .def = .{ .steps = &.{.{ .cmd = 41152 }} } },
    .{ .name = "ToggleShowFx1", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX1" }} } },
    .{ .name = "ToggleShowFx2", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX2" }} } },
    .{ .name = "ToggleShowFx3", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX3" }} } },
    .{ .name = "ToggleShowFx4", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX4" }} } },
    .{ .name = "ToggleShowFx5", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX5" }} } },
    .{ .name = "ToggleShowFx6", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX6" }} } },
    .{ .name = "ToggleShowFx7", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX7" }} } },
    .{ .name = "ToggleShowFx8", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFLOATFX8" }} } },
    .{ .name = "ToggleShowFxChain", .def = .{ .steps = &.{.{ .named = "_S&M_TOGLFXCHAIN" }} } },
    .{ .name = "ToggleShowTakeFxChain", .def = .{ .steps = &.{.{ .cmd = 40638 }} } },
    .{ .name = "ToggleShowFx", .def = .{ .steps = &.{.{ .named = "_S&M_WNTGL5" }} } },
    .{ .name = "ToggleShowSelectedEnvelope", .def = .{ .steps = &.{.{ .cmd = 40884 }} } },
    .{ .name = "ToggleShowTracksInMixer", .def = .{ .steps = &.{.{ .cmd = 41592 }} } },
    .{ .name = "ToggleSnap", .def = .{ .steps = &.{.{ .cmd = 1157 }} } },
    .{ .name = "ToggleSolo", .def = .{ .steps = &.{.{ .cmd = 7 }} } },
    .{ .name = "ToggleSoloItem", .def = .{ .steps = &.{.{ .cmd = 41557 }} } },
    .{ .name = "UnsoloAllItems", .def = .{ .steps = &.{.{ .cmd = 41185 }} } },
    .{ .name = "ToggleAutomaticRecordArm", .def = .{ .steps = &.{.{ .cmd = 40740 }} } },
    .{ .name = "ToggleStopAtEndOfTimeSelectionIfNoRepeat", .def = .{ .steps = &.{.{ .cmd = 41834 }} } },
    .{ .name = "ToggleViewMixer", .def = .{ .steps = &.{.{ .cmd = 40078 }} } },
    .{ .name = "ToggleVolumeEnvelope", .def = .{ .steps = &.{.{ .cmd = 40406 }} } },
    .{ .name = "SelectWidthEnvelope", .def = .{ .steps = &.{.{ .cmd = 41870 }} } },
    .{ .name = "ToggleTakeMuteEnvelope", .def = .{ .steps = &.{.{ .cmd = 40695 }} } },
    .{ .name = "ToggleTakePanEnvelope", .def = .{ .steps = &.{.{ .cmd = 40694 }} } },
    .{ .name = "ToggleTakePitchEnvelope", .def = .{ .steps = &.{.{ .cmd = 41612 }} } },
    .{ .name = "ToggleTakeVolumeEnvelope", .def = .{ .steps = &.{.{ .cmd = 40693 }} } },
    .{ .name = "SetTrackInputToMatchFirstSelected", .def = .{ .steps = &.{.{ .named = "_SWS_INPUTMATCH" }} } },
    .{ .name = "TrackToggleSendToParent", .def = .{ .steps = &.{.{ .named = "_SWS_TOGMPSEND" }} } },
    // trims
    .{ .name = "TrimItemLeftEdge", .def = .{ .steps = &.{.{ .cmd = 41305 }} } },
    .{ .name = "TrimItemRightEdge", .def = .{ .steps = &.{.{ .cmd = 41311 }} } },
    .{ .name = "TrimSelectedNoteLeftEdgeToEditCursor", .def = .{ .steps = &.{.{ .cmd = 40790 }} } },
    .{ .name = "TrimSelectedNoteRightEdgeToEditCursor", .def = .{ .steps = &.{.{ .cmd = 40791 }} } },
    .{ .name = "UnarmAllEnvelopes", .def = .{ .steps = &.{.{ .cmd = 41163 }} } },
    .{ .name = "UnarmSelectedTracks", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_SELTRAX_RECUNARMED" }} } },
    .{ .name = "UncollapseFolder", .def = .{ .steps = &.{.{ .named = "_SWS_UNCOLLAPSE" }} } },
    .{ .name = "Undo", .def = .{ .steps = &.{.{ .cmd = 40029 }}, .prefix_repetition_count = true } },
    .{ .name = "UnfreezeTrack", .def = .{ .steps = &.{.{ .cmd = 41644 }} } },
    .{ .name = "UnmuteAllTracks", .def = .{ .steps = &.{.{ .cmd = 40339 }} } },
    .{ .name = "UnselectAllEvents", .def = .{ .steps = &.{.{ .cmd = 40214 }}, .midi_command = true } },
    .{ .name = "UnselectEnvelopePoints", .def = .{ .steps = &.{.{ .cmd = 40331 }} } },
    .{ .name = "UnselectItems", .def = .{ .steps = &.{.{ .cmd = 40289 }} } },
    .{ .name = "UnselectTracks", .def = .{ .steps = &.{.{ .cmd = 40297 }} } },
    .{ .name = "UnsoloAllTracks", .def = .{ .steps = &.{.{ .cmd = 40340 }} } },
    .{ .name = "VerticalScrollEnd", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_TVPAGEEND" }} } },
    .{ .name = "VerticalScrollStart", .def = .{ .steps = &.{.{ .named = "_XENAKIOS_TVPAGEHOME" }} } },
    .{ .name = "ToggleShowInputFxChain", .def = .{ .steps = &.{.{ .cmd = 40844 }} } },
    .{ .name = "ViewFxChainMaster", .def = .{ .steps = &.{.{ .cmd = 40846 }} } },
    // zoom
    .{ .name = "ZoomAllItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectAllItems" }, .{ .action = "ZoomItemSelection" }, .{ .action = "RestoreItemSelection" } } } },
    .{ .name = "ZoomAllTracks", .def = .{ .steps = &.{ .{ .action = "SaveTrackSelection" }, .{ .action = "SelectAllTracks" }, .{ .action = "ZoomTrackSelection" }, .{ .action = "RestoreTrackSelection" } } } },
    .{ .name = "ZoomInHoriz", .def = .{ .steps = &.{.{ .cmd = 1012 }}, .prefix_repetition_count = true } },
    .{ .name = "ZoomInVert", .def = .{ .steps = &.{.{ .cmd = 40111 }}, .prefix_repetition_count = true } },
    .{ .name = "ZoomItemSelection", .def = .{ .steps = &.{.{ .named = "_SWS_HZOOMITEMS" }} } },
    .{ .name = "ZoomOutHoriz", .def = .{ .steps = &.{.{ .cmd = 1011 }}, .prefix_repetition_count = true } },
    .{ .name = "ZoomOutVert", .def = .{ .steps = &.{.{ .cmd = 40112 }}, .prefix_repetition_count = true } },
    .{ .name = "ZoomProjectTimeline", .def = .{ .steps = &.{.{ .cmd = 40295 }} } },
    .{ .name = "ZoomProject", .def = .{ .steps = &.{ .{ .action = "ZoomAllTracks" }, .{ .action = "ZoomAllItems" } } } },
    .{ .name = "ZoomRedo", .def = .{ .steps = &.{.{ .named = "_SWS_REDOZOOM" }}, .prefix_repetition_count = true } },
    .{ .name = "ZoomTimeAndTrackSelection", .def = .{ .steps = &.{ .{ .action = "ZoomTrackSelection" }, .{ .action = "ZoomTimeSelection" } } } },
    .{ .name = "ZoomTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40031 }} } },
    .{ .name = "ZoomTrackSelection", .def = .{ .steps = &.{.{ .named = "_SWS_VZOOMFITMIN" }} } },
    .{ .name = "ZoomUndo", .def = .{ .steps = &.{.{ .named = "_SWS_UNDOZOOM" }}, .prefix_repetition_count = true } },
    .{ .name = "NudgeTrackVolumeDown", .def = .{ .steps = &.{.{ .cmd = 40116 }} } }, // 0.05 dB
    .{ .name = "PlayAndSkipTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40317 }} } },
    .{ .name = "LengthenNotes", .def = .{ .steps = &.{.{ .cmd = 40446 }}, .midi_command = true } },
    .{ .name = "ShortenNotes", .def = .{ .steps = &.{.{ .cmd = 40447 }}, .midi_command = true } },
    .{ .name = "ToggleUsedCC", .def = .{ .steps = &.{.{ .named = "_S&M_ME_PIANO_CYCLACTION3" }}, .midi_command = true } },
    // note insertion (UnselectAllEvents + insert-note-at-pitch command)
    .{ .name = "InsertG", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41089 } }, .midi_command = true } },
    .{ .name = "InsertGb", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41088 } }, .midi_command = true } },
    .{ .name = "InsertF", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41087 } }, .midi_command = true } },
    .{ .name = "InsertE", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41086 } }, .midi_command = true } },
    .{ .name = "InsertEb", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41085 } }, .midi_command = true } },
    .{ .name = "InsertD", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41084 } }, .midi_command = true } },
    .{ .name = "InsertDb", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41083 } }, .midi_command = true } },
    .{ .name = "InsertC", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41082 } }, .midi_command = true } },
    .{ .name = "InsertB", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41093 } }, .midi_command = true } },
    .{ .name = "InsertBb", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41092 } }, .midi_command = true } },
    .{ .name = "InsertA", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41091 } }, .midi_command = true } },
    .{ .name = "InsertAb", .def = .{ .steps = &.{ .{ .action = "UnselectAllEvents" }, .{ .cmd = 41090 } }, .midi_command = true } },
    .{ .name = "InsertChordG", .def = .{ .steps = &.{ .{ .action = "InsertG" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordGb", .def = .{ .steps = &.{ .{ .action = "InsertGb" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordF", .def = .{ .steps = &.{ .{ .action = "InsertF" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordE", .def = .{ .steps = &.{ .{ .action = "InsertE" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordEb", .def = .{ .steps = &.{ .{ .action = "InsertEb" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordD", .def = .{ .steps = &.{ .{ .action = "InsertD" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordDb", .def = .{ .steps = &.{ .{ .action = "InsertDb" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordC", .def = .{ .steps = &.{ .{ .action = "InsertC" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordB", .def = .{ .steps = &.{ .{ .action = "InsertB" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordBb", .def = .{ .steps = &.{ .{ .action = "InsertBb" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordA", .def = .{ .steps = &.{ .{ .action = "InsertA" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "InsertChordAb", .def = .{ .steps = &.{ .{ .action = "InsertAb" }, .{ .action = "LeftMidiGridDivision" } }, .midi_command = true } },
    .{ .name = "CurrentTrack", .def = .{} }, // placeholder selector (empty table in Lua)
    .{ .name = "IncreaseGrid", .def = .{ .steps = &.{.{ .cmd = 40786 }}, .prefix_repetition_count = true } },
    .{ .name = "DecreaseGrid", .def = .{ .steps = &.{.{ .cmd = 40783 }}, .prefix_repetition_count = true } },
    .{ .name = "QuitReaper", .def = .{ .steps = &.{.{ .cmd = 40004 }} } },
    .{ .name = "NextTransientInItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsOnTrack" }, .{ .cmd = 40375 }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "PrevTransientInItems", .def = .{ .steps = &.{ .{ .action = "SaveItemSelection" }, .{ .action = "SelectItemsOnTrack" }, .{ .cmd = 40376 }, .{ .action = "RestoreItemSelection" } }, .prefix_repetition_count = true } },
    .{ .name = "ActivateNextMidiTrack", .def = .{ .steps = &.{.{ .cmd = 40835 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "ActivatePrevMidiTrack", .def = .{ .steps = &.{.{ .cmd = 40836 }}, .midi_command = true, .prefix_repetition_count = true } },
    .{ .name = "ReverseItems", .def = .{ .steps = &.{.{ .cmd = 41051 }} } },
    // item pitch
    .{ .name = "PitchItemDownSemi", .def = .{ .steps = &.{.{ .cmd = 40205 }}, .prefix_repetition_count = true } },
    .{ .name = "PitchItemUpSemi", .def = .{ .steps = &.{.{ .cmd = 40204 }}, .prefix_repetition_count = true } },
    .{ .name = "PitchItemDownOct", .def = .{ .steps = &.{.{ .cmd = 40516 }}, .prefix_repetition_count = true } },
    .{ .name = "PitchItemUpOct", .def = .{ .steps = &.{.{ .cmd = 40515 }}, .prefix_repetition_count = true } },
    .{ .name = "ShowEnvelopeLastTouchedFxParam", .def = .{ .steps = &.{.{ .cmd = 41142 }} } },
    .{ .name = "DynamicSplit", .def = .{ .steps = &.{.{ .cmd = 40760 }} } },
    .{ .name = "SplitAtStretchMarkers", .def = .{ .steps = &.{.{ .named = "_BR_SPLIT_SEL_ITEM_STRETCH_MARKERS" }} } },
    .{ .name = "ClearItemStretchMarkers", .def = .{ .steps = &.{.{ .cmd = 41844 }} } },
    // FIXED: Lua's 2nd step "ClearItemTransients" is defined nowhere — dropped.
    .{ .name = "ClearTransientsAndStretchMarkers", .def = .{ .steps = &.{.{ .action = "ClearItemStretchMarkers" }} } },
    .{ .name = "MediaExplorer", .def = .{ .steps = &.{.{ .cmd = 50124 }} } },
    .{ .name = "LoopItem", .def = .{ .steps = &.{.{ .named = "_SWS_LOOPITEMSECTION" }} } },
    // envelope points
    .{ .name = "ClearEnvelopePointSelection", .def = .{ .steps = &.{.{ .cmd = 40331 }} } },
    .{ .name = "InsertEnvelopePoint", .def = .{ .steps = &.{ .{ .action = "ClearEnvelopePointSelection" }, .{ .cmd = 40106 } } } },
    .{ .name = "InsertEnvelopePointsAtSelection", .def = .{ .steps = &.{.{ .named = "_BR_INSERT_2_ENV_POINT_TIME_SEL" }} } },
    .{ .name = "BezierPointShape", .def = .{ .steps = &.{.{ .cmd = 40683 }} } },
    .{ .name = "FastEndPointShape", .def = .{ .steps = &.{.{ .cmd = 40429 }} } },
    .{ .name = "FastStartPointShape", .def = .{ .steps = &.{.{ .cmd = 40428 }} } },
    .{ .name = "LinearPointShape", .def = .{ .steps = &.{.{ .cmd = 40189 }} } },
    .{ .name = "SlowStartEndPointShape", .def = .{ .steps = &.{.{ .cmd = 40424 }} } },
    .{ .name = "SquarePointShape", .def = .{ .steps = &.{.{ .cmd = 40190 }} } },
    .{ .name = "SavePointSelection", .def = .{ .steps = &.{.{ .named = "_BR_SAVE_ENV_SEL_SLOT_1" }} } },
    .{ .name = "RestorePointSelection", .def = .{ .steps = &.{.{ .named = "_BR_RESTORE_ENV_SEL_SLOT_1" }} } },
    .{ .name = "AllTrackEnvelopePoints", .def = .{ .steps = &.{ .{ .action = "SavePointSelection" }, .{ .action = "SelectAllPoints" }, .{ .action = "SelectedPoints" }, .{ .action = "RestorePointSelection" } } } },
    .{ .name = "SelectAllPoints", .def = .{ .steps = &.{.{ .cmd = 40332 }} } },
    // OMITTED: commandIdLookup — custom.dev.commandIdLookup does not exist in
    // the Lua source (broken nil reference).
    .{ .name = "ProjectBay", .def = .{ .steps = &.{.{ .cmd = 41157 }} } },
    .{ .name = "AddTextOrnament", .def = .{ .steps = &.{.{ .cmd = 41780 }}, .midi_command = true } },
    .{ .name = "ImplodeItemsOntoSingleTrack", .def = .{ .steps = &.{ .{ .cmd = 40644 }, .{ .action = "GlueItemsIgnoringTimeSelection" } } } },
    .{ .name = "forceSelectedNotesToKey", .def = .{ .steps = &.{.{ .cmd = 40767 }}, .midi_command = true } },
    .{ .name = "SplitAtMouse", .def = .{ .steps = &.{.{ .cmd = 42575 }} } },
    .{ .name = "ExplodeNoteRows", .def = .{ .steps = &.{.{ .cmd = 40920 }} } },
    .{ .name = "SelectPointsTimeSelection", .def = .{ .steps = &.{.{ .cmd = 40330 }} } },
    .{ .name = "InvertSelectedPoints", .def = .{ .steps = &.{.{ .cmd = 40334 }} } },
    .{ .name = "ToggleShowEnvelopesForTracks", .def = .{ .steps = &.{.{ .cmd = 40890 }} } },
    // markers / screensets / time-sel tail
    .{ .name = "InsertProjectMarker", .def = .{ .steps = &.{.{ .cmd = 40157 }} } },
    .{ .name = "InsertTakeMarker", .def = .{ .steps = &.{.{ .cmd = 42385 }} } },
    .{ .name = "NextProjectMarker", .def = .{ .steps = &.{.{ .cmd = 40173 }}, .prefix_repetition_count = true } },
    .{ .name = "PreviousProjectMarker", .def = .{ .steps = &.{.{ .cmd = 40172 }}, .prefix_repetition_count = true } },
    .{ .name = "NextTakeMarker", .def = .{ .steps = &.{.{ .cmd = 42394 }}, .prefix_repetition_count = true } },
    .{ .name = "PrevTakeMarker", .def = .{ .steps = &.{.{ .cmd = 42393 }}, .prefix_repetition_count = true } },
    .{ .name = "SaveTrkScreenSet1", .def = .{ .steps = &.{.{ .cmd = 40464 }} } },
    .{ .name = "LoadTrkScreenSet1", .def = .{ .steps = &.{.{ .cmd = 40444 }} } },
    .{ .name = "MuteEvents", .def = .{ .steps = &.{.{ .cmd = 40055 }}, .midi_command = true } },
    .{ .name = "RemoveContentsOfTimeSel", .def = .{ .steps = &.{.{ .cmd = 40201 }} } },
    .{ .name = "MoveTimeSelToCursor", .def = .{ .steps = &.{.{ .cmd = 40396 }} } },
    .{ .name = "CopyTimeSelToCursor", .def = .{ .steps = &.{.{ .cmd = 40397 }} } },
    .{ .name = "InsertSilence", .def = .{ .steps = &.{.{ .named = "_S&M_INSERT_SILENCE_MB" }} } },
};

// ---------------------------------------------------------------------------
// Skipped Lua-function actions (need native Zig implementations).
// Grouped by source module under reavim/internal/. Names referenced above as
// .action steps will log as stubs until their entry is ported.
//
// custom_actions/selection.lua:
//   BigItem, Item, ProjectTimeline, Region, SelectOnlyCurrentTrack
// custom_actions/custom_actions.lua:
//   ClearTimeSelection, ClearSelectedTimeline, SetGridDivision,
//   SetMidiGridDivision, SplitItemsAtTimeSelection
// custom_actions/movement.lua:
//   FirstItemStart, LastItemEnd, FirstTrack, LastTrack, NextBigItemEnd,
//   NextBigItemStart, NextItemEnd, NextItemStart, PrevBigItemStart,
//   PrevItemStart, ProjectEnd, ProjectStart, SnappedPosition,
//   FirstTrackWithItem, TrackWithNumber, StoreCursorPosition,
//   RestoreCursorPosition, jumpToBar, MidiItemStart, MidiItemEnd,
//   MoveItemUp, MoveItemDown
// custom_actions/envelope.lua:
//   DeleteEnvelopePoints, SelectEnvelopePoints, SelectedPoints, SetPointMin,
//   SetPointMax, SetPointCenter, MoveEnvelopePointDown, MoveEnvelopePointUp,
//   InsertToggleAtTimeSelection
// custom_actions/midi.lua:
//   PitchCursorToSelectedNote, JumpToNextNote, JumpToPrevNote,
//   NextBigNoteEnd, NextBigNoteStart, PrevBigNoteEnd, PrevBigNoteStart,
//   toggleKeySnap, CloseUndockedMidiEditorOrPassToMainWindow
// custom_actions/items.lua:
//   PasteItemBeforeCursor, Set2msFades, TrimRightEdgeFromMouse,
//   TrimLeftEdgeFromMouse, FadeItemInFromMouse, FadeItemOutFromMouse,
//   SplitItemsAtNoteStart, StretchItemEndToCursor, StretchItemStartToCursor
// custom_actions/tracks.lua:
//   toggleSoloExclusive, TrackVolumeUp3, TrackVolumeDown3,
//   RenameTrackToVstiPresetName
// custom_actions/drums.lua:
//   Flam, Ras3, Ras5, Crescendo, Decrescendo, QuantizeTool
// custom_actions/dev.lua:
//   Repl, devAction, FxDevices
// custom_actions/routing.lua:
//   RouteToBusses, BuildBusses
// custom_actions/fx.lua:
//   InsertFxAtSlot
// custom_actions/midi_arranging.lua:
//   ExplodeRoutineFromAnnotations, soliHarmonize, insertChordSymbol
// custom_actions/kawa.lua:
//   SelectBottomNotes, SelectTopNotes, SelectMiddleNotes, SelectAllButTop,
//   SelectAllButBottom, SelectAllButMiddle, drop2, drop3, drop24,
//   doubleTopOctUp, doubleBottomOctDown, doubleOctDown, doubleSeventhDown,
//   doubleSixthDown, doubleFifthDown, doubleFourthDown, doubleThirdDown,
//   doubleOctUp, doubleSeventhUp, doubleSixthUp, doubleFifthUp,
//   doubleFourthUp, doubleThirdUp
// custom_actions/midi_controller.lua:
//   VrtlBtn1, VrtlBtn2, VrtlBtn3, VrtlBtn4, VrtlBtn5, VrtlBtn6, VrtlBtn7,
//   VrtlBtn8, VrtlBtn9, VrtlBtn10, VrtlBtn11, VrtlBtn12, VrtlBtn13,
//   VrtlBtn14, VrtlBtn15, VrtlBtn16
// custom_actions/pasteRhythm.lua:
//   pasteRhythmToPitches
// library/library.lua:
//   ResetFeedbackWindow, MatchTrackNameBackward, MatchTrackNameForward,
//   RepeatTrackNameMatchBackward, RepeatTrackNameMatchForward
// library/marks.lua (register actions):
//   Mark, DeleteMark, MarkedRegion, MarkedTimelinePosition, MarkedTracks
// library/state.lua: already ported in lib_state.zig (SetModeNormal,
//   SetModeVisualTrack, SetModeVisualTimeline, SwitchTimelineSelectionSide).
// Broken Lua refs omitted entirely: RecallMark, SetModeRecord,
//   commandIdLookup.
// ---------------------------------------------------------------------------
